request_headers = ['Accept',
				   'Accept-Charset',
				   'Accept-Encoding',
				   'Accept-Language',
				   'Accept-Datetime',
				   'Access-Control-Request-Method',
				   'Access-Control-Request-Headers',
				   'Authorization',
				   'Cache-Control',
				   'Connection',
				   'Cookie',
				   'Content-Length	',
				   'Content-MD5',
				   'Content-Type',
				   'Date',
				   'Expect',
				   'Forwarded',
				   'From',
				   'Host',
				   'If-Match',
				   'If-Modified-Since',
				   'If-None-Match',
				   'If-Range',
				   'If-Unmodified-Since',
				   'Max-Forwards',
				   'Origin',
				   'Pragma',
				   'Proxy-Authorization',
				   'Range',
				   'Referer',
				   'TE',
				   'User-Agent',
				   'Upgrade',
				   'Via',
				   'Warning'
				   'X-Requested-With'
				   'X-Forwarded-For',
				   'X-Forwarded-Host',
				   'X-Forwarded-Proto',
				   'X-Http-Method-Override',
				   'Proxy-Connection',
				   'X-Request-ID',
				   'X-Request-ID']

csrf_headers = [
				'X-Csrf-Token',
				'X-CSRFToken',
				'X-XSRF-TOKEN']
				