version: '3'

services:
  astra-mongo:
    image: "mongo"
    container_name: "astra-mongo"
    restart: unless-stopped

  astra-gui:
    build: .
    image: "astra"
    container_name: "astra-gui"
    ports:
      - "8094:8094"
    environment:
      MONGO_HOST: astra-mongo
    depends_on:
      - astra-mongo
    restart: unless-stopped
