version: '3.8'

services:
  devcontainer:
    build: 
      context: "../"
      dockerfile: "./.devcontainer/Dockerfile"
    volumes:
      - ../:/app
    command: "sleep infinity"
    depends_on: [ "mongo" ]
    ports:
      - "8094:8094"

  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    healthcheck:
      test: [ "CMD", "bash", "-c", "echo 'db.runCommand(\"ping\").ok' | mongosh --quiet" ]
      interval: 10s
      timeout: 5s
      retries: 4
      start_period: 1s

  rabbit:
    image: rabbitmq:3
    ports:
      - "5672:5672"